#      .   .               <Leviathan>
#     .:...::     Command Name // !pangrams
#    .::   ::.     Description // Random pangram.
# ..:;;. ' .;;:..        Usage // !pangrams
#    .  '''  .     Permissions // Public
#     :;,:,;:         Listener // All
#     :     :        Copyright // 2005 AiChaos Inc.

sub pangrams {
	my ($self,$client,$msg) = @_;

	# Array of all English pangrams.
	my @pangrams = (
		'A quick brown fox jumps over the lazy dog.',
		'A large fawn jumped quickly over white zinc boxes.',
		'A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.',
		'A quick movement of the enemy will jeopardize six gunboats.',
		'About sixty codfish eggs will make a quarter pound of very fizzy jelly.',
		'Alfredo just must bring very exciting news to the plaza quickly.',
		'All questions asked by five watch experts amazed the judge.',
		'An inspired calligrapher can create pages of beauty using stick ink, quill, brush, pick-axe, buzz saw, or even strawberry jam.',
		'Astronaut Quincy B. Zack defies gravity with six jet fuel pumps.',
		'Back in June we delivered oxygen equipment of the same size.',
		'Back in my quaint garden jaunty zinnias vie with flaunting phlox.',
		'Big July earthquakes confound zany experimental vow.',
		'Blowzy red vixens fight for a quick jump.',
		'Brawny gods just flocked up to quiz and vex him.',
		'Breezily jangling ,416,857,209 wise advertiser ambles to the bank, his exchequer amplified.',
		'Cozy sphinx waves quart jug of bad milk.',
		'Crazy Fredericka bought many very exquisite opal jewels.',
		'Dumpy kibitzer jingles as exchequer overflows.',
		'Ebenezer unexpectedly bagged two tranquil aardvarks with his jiffy vacuum cleaner.',
		'Exquisite farm wench gives body jolt to prize stinker.',
		'Fabled reader with jaded, roving eye seized by quickened impulse to expand budget.',
		'Five big quacking zephyrs jolt my wax bed.',
		'Five or six big jet planes zoomed quickly by the tower.',
		'Five wine experts jokingly quizzed chablis sample.',
		'Five wine experts jokingly quizzed sample chablis.',
		'Fjord nymphs\' XV beg quick waltz.',
		'Fjord-vext cwm-bank glyphs quiz.',
		'For only , jolly housewives made "inexpensive" meals using quick-frozen vegetables.',
		'Forsaking monastic tradition, twelve jovial friars gave up their vocation for a questionable existence on the flying trapeze.',
		'Fred specialized in the job of making very quaint wax toys.',
		'Freight to me sixty dozen quart jars and twelve black pans.',
		'Grumpy wizards make toxic brew for the evil Queen and Jack.',
		'Hark! Toxic jungle water vipers quietly drop on zebras for meals!',
		'How jolly vexing a fumble to drop zucchini in the quicksand!',
		'How quickly daft jumping zebras vex.',
		'How razorback-jumping frogs can level six piqued gymnasts!',
		'How vexing a fumble to drop a jolly zucchini in the quicksand.',
		'Jack amazed a few girls by dropping the antique onyx vase!',
		'Jackdaws love my big sphinx of quartz.',
		'Jaded zombies acted quaintly but kept driving their oxen forward.',
		'Jail zesty vixen who grabbed pay from quack.',
		'Jay visited back home and gazed upon a brown fox and quail.',
		'Jeb quickly drove a few extra miles on the glazed pavement.',
		'Jelly-like above the high wire, six quaking pachyderms kept the climax of the extravaganza in a dazzling state of flux.',
		'Jim just quit and packed extra bags for Liz Owen.',
		'Jimmy and Zack, the police explained, were last seen diving into a field of buttered quahogs.',
		'July earthquakes confound zany experimental vow.',
		'Just keep examining every low bid quoted for zinc etchings.',
		'Just work for improved basic techniques to maximize your typing skill.',
		'King Alexander was just partly overcome after quizzing Diogenes in his tub.',
		'Lazy movers quit hard-packing of papier-mache jewelry boxes.',
		'Many big jackdaws quickly zipped over the fox pen.',
		'Many-wived Jack laughs at probes of sex quiz.',
		'Martin J. Hixeypozer quickly began his first word.',
		'May Jo equal the fine record by solving six puzzles a week?',
		'Mix Zapf with Veljovic and get quirky Beziers.',
		'Mr. Jock, TV quiz Ph.D., bags few lynx.',
		'Murky haze enveloped a city as jarring quakes broke fourty-six windows.',
		'My grandfather picks up quartz and valuable onyx jewels.',
		'My help squeezed back in again and joined the weavers after six.',
		'My help squeezed in again after six and joined the weavers. ',
		'New farm hand (picking just six quinces) proves strong but lazy.',
		'New farmhand proves strong but lazy, picking just six quinces.',
		'No kidding, Lorenzo called off his trip to visit Mexico City just because they told him the conquistadores were extinct.',
		'Now is the time for all brown dogs to jump over the lazy lynx.',
		'Pack my box with five dozen liquor jugs.',
		'Perhaps President Clinton\'s amazing sax skills will be judged quite favorably.',
		'Playing jazz vibe chords quickly excites my wife.',
		'Portez ce vieux whisky au juge blond qui fume.',
		'Puzzled women bequeath jerks very exotic gifts.',
		'Questions of a zealous nature have become by degrees petty waxen jokes.',
		'Quick jigs for waltz vex bad nymph.',
		'Quick wafting zephyrs vex bold Jim.',
		'Quick zephyrs blow, vexing daft Jim.',
		'Quixotic Republicans vet first key zero-growth jeremiad.',
		'Six big devils from Japan quickly forgot how to waltz.',
		'Six big juicy steaks sizzled in a pan as five workmen left the quarry.',
		'Six crazy kings vowed to abolish my quite pitiful jousts.',
		'Six quite crazy kings vowed to abolish my pitiful jousts.',
		'Sixty zippers were quickly picked from the woven jute bag.',
		'Sphinx of black quartz judge my vow.',
		'Squdgy fez, blank jimp crwth vox!',
		'Suez sailor vomits jauntily abaft while waxing parquet decks.',
		'Sympathizing would fix Quaker objectives.',
		'The exodus of jazzy pigeons is craved by squeamish walkers.',
		'The five boxing wizards jump quickly.',
		'The job of waxing linoleum frequently peeves chintzy kids.',
		'The juke box music puzzled a gentle visitor from a quaint valley town.',
		'The July sun caused a fragment of black pine wax to ooze on the velvet quilt.',
		'The July sun caused a fragment of pine wax to ooze on the black velvet quilt.',
		'The quick brown fox jumps over a lazy dog.',
		'The risque gown maked a very brazen exposure of juicy flesh.',
		'The sex life of the woodchuck is a provocative question for most vertebrate zoology majors.',
		'The vixen jumped quickly on her foe barking with zeal.',
		'Turgid saxophones blew over Mick\'s jazzy quiff.',
		'Two hardy boxing kangaroos jet from Sydney to Zanzibar on quicksilver pinions.',
		'Verbatim reports were quickly given by Jim Fox to his amazed audience.',
		'Verily the dark ex-Jew quit Zionism, preferring the cabala.',
		'Viewing quizzical abstracts mixed up hefty jocks.',
		'Waltz, nymph, for quick jigs vex Bud.',
		'Was there a quorum of able whizzkids gravely exciting the jaded fish at ATypI?',
		'Watch all five questions asked by experts amaze the judge.',
		'We have just quoted on nine dozen boxes of gray lamp wicks.',
		'We promptly judged antique ivory buckles for the next prize.',
		'West quickly gave Bert handsome prizes for six juicy plums.',
		'When we go back to Juarez, Mexico, do we fly over picturesque Arizona?',
		'While waxing parquet decks, Suez sailors vomit jaunitly abaft.',
		'Will Major Douglas be expected to take this true-false quiz very soon?',
		'William Jex quickly caught five dozen Republicans.',
		'William said that everything about his jacket was in quite good condition except for the zipper.',
	);

	# Send a random one.
	return $pangrams [ int(rand(scalar(@pangrams))) ];
}
{
	Category => 'Fun Stuff',
	Description => 'Random pangram.',
	Usage => '!pangrams',
	Listener => 'All',
};