#      .   .             <CKS Juggernaut>
#     .:...::     Command Name // !virus
#    .::   ::.     Description // Random virus jokes.
# ..:;;. ' .;;:..        Usage // !virus
#    .  '''  .     Permissions // Public
#     :;,:,;:         Listener // All Listeners
#     :     :        Copyright // 2004 Chaos AI Technology

sub virus {
	my ($self,$client,$msg,$listener) = @_;

	# Our array of viruses...
	my @virus = (
		"BIN LADEN VIRUS - Continues to hide in its own set of network connections.",
		"GEORGE W BUSH VIRUS - Intermittently masks the pixel colors on your screen, so that you never get the whole picture.",
		"JOKE VIRUS - Poses as a harmless list of funny computer virus names!",
		"7TH DAY ADVENTIST VIRUS - Very destructive - disables your system every Saturday, but let's it start up again on Sunday morning.",
		"ADAM AND EVE VIRUS - Takes a couple of bytes out of your Apple computer.",
		"AL GORE UNIX VIRUS - Whenever you inquire about one of your environment variables, it shows you the current settings, but then tacks on an alarmist message concerning the future of the variable.",
		"AIRLINE VIRUS - You're in Dallas, but your data is in Singapore.",
		"ARNOLD SCHWARZENEGGER VIRUS - Terminates and stays resident. It vill be bahk.",
		"AT\&T VIRUS - Every three minutes it tells you what great service you are getting.",
		"BAPTIST VIRUS - Immerses your hard-drive in water, secretly drinks beer on Friday night, memory chips go for a smoke behind your computer when you hit pause.",
		"BIRTHDAY VIRUS - Keeps advancing your clock by another year.",
		"BOB DOLE VIRUS - Could be virulent, but it's been around too long to be much of a threat.",
		"BORIS YELZIN VIRUS - It reformats your drive and alters your PC's basic operating principles every ten minutes, making it completely inoperative. Meanwhile, an on screen message begs you to be patient and wait 90 days for results.",
		"BOSNIA-HERTZEGOVINA VIRUS - Under the influence of this Eastern European virus, your PC's components continuously break down into tiny, squabbling factions.",
		"C\*A\*M\*P\* VIRUS - Compuserve\*America Online\*MicrosoftNetwork\*Prodigy\* Need I say more?",
		"CHARISMATIC VIRUS - Promises a blessing on the 'Next' click perpetually.",
		"CHICAGO CUBS VIRUS - Your PC makes frequent mistakes and comes in last in the reviews, but you still love it.",
		"CHRISTIAN SCIENCE VIRUS - Your hard drive isn't really down, you just think it is.",
		"CLEVELAND INDIANS VIRUS - Makes your 486/50 machine perform like a 286AT.",
		"CLINTON VIRUS - Gives you a 7\" hard drive with no memory.",
		"COLIN POWELL VIRUS - Makes its presence known, but doesn't do anything. Secretly, you wish it would.",
		"CONGRESSIONAL VIRUS - \#1 The computer locks up, screen splits erratically with a message appearing on each half blaming the other side for the problem.",
		"CONGRESSIONAL VIRUS - \#2 The computer locks up, and the screen splits in half with the same message appearing on each side of the screen. The message says that the blame for the gridlock is cause by the other side.",
		"CONGRESSIONAL VIRUS - \#3 Runs every program on the hard drive simultaneously but doesn't allow the user to accomplish anything.",
		"CONGRESSIONAL VIRUS - \#4 Overdraws your disk space.",
		"DAN QUAYLE VIRUS - \#1 Prevents your system from spawning any child process with joining into a binary network.",
		"DAN QUAYLE VIRUS - \#2 Their is sumthing rong wit your komputer, ewe jsut cant figyour out watt!",
		"DAN QUAYLE VIRUS - \#3 Said to cause speling erors in files stored on your disk.",
		"DAN QUAYLE VIRUS - \#4 Forces your computer to play PGA TOUR from 10am to 4pm, six days a week.",
		"DAVID DUKE VIRUS - Makes your screen go completely white.",
		"DISNEY VIRUS - Everything in your computer goes goofy.",
		"DR. HANNIBAL LECTER VIRUS - It eats the heart out of your PC with some fava beans and a nice Chianti.",
		"ELLEN DEGENERES VIRUS - Disks can no longer be inserted.",
		"ELVIS VIRUS - Your computer gets fat, slow and lazy, then self-destructs -- only to resurface at shopping malls and service stations across rural America.",
		"EPISCOPAL VIRUS - All files self-delete after a pre-determined time, so that the hard drive never fills to more than 30\% of capacity.",
		"E.T. VIRUS - Locks up your modem by phoning home.",
		"FEDERAL BUREAUCRAT VIRUS - Divides your hard disk into hundreds of little units, each of which does practically nothing, but all of which claim to be the most important part of your computer.",
		"FREUDIAN VIRUS - \#1 Your computer becomes obsessed with marrying its own motherboard.",
		"FREUDIAN VIRUS - \#2 Your computer becomes envious of your friend's hard drive.",
		"GALLUP VIRUS - Sixty percent of the PCs infected will lose 38 percent of their data 14 percent of the time (plus or minute a 3.5 percent margin of error).",
		"GEORGE BUSH VIRUS - It starts by boldly saying, 'Read my docs... no new files!' on the screen. It proceeds to fill up all the free space on your hard drive with new files, then blames it on the CONGRESSIONAL VIRUS.",
		"GEORGE MICHAELS VIRUS - Runs its course, occasionally releasing data buildup.",
		"GOVERNMENT ECONOMIST VIRUS - Nothing works, but all your diagnostic software says everything is fine.",
		"GRIDLOCK VIRUS - Keeps shuffling information that it calls 'bills' between your CPU and BUS, sending messages like 'House Bill \#xxxx is unacceptable to Senate'. Never gets any work done.",
		"HEALTH CARE VIRUS - Tests your system for a day, finds nothing wrong, and sends you a bill for \$4,500.",
		"HILLARY RODHAM CLINTON VIRUS - \#1 Files disappear, only to reappear mysteriously a year later, in another directory.",
		"HILLARY RODHAM CLINTON VIRUS - \#2 Instantly turns 1K of disk space into 1 Meg.",
		"IMELDA MARCOS VIRUS - Sings you a song (slightly off key) on boot up, then subtracts money from your Quicken account and spends it all on expensive shoes it purchases through Prodigy.",
		"JACK KEVORKIAN VIRUS - \#1 Deletes all old files.",
		"JACK KEVORKIAN VIRUS - \#2 Helps your computer shut down as an act of mercy.",
		"JACK KEVORKIAN VIRUS - \#3 Enables irreparably damaged files to delete themselves.",
		"JACK KEVORKIAN VIRUS - \#4 Helps your computer shut down whenever you want it to, but it can never be reset of rebotted again. This virus only attacks Terminal Cases.",
		"JANE FONDA VIRUS - Attacks your hard drive's FAT.",
		"JEHOVAH'S WITNESS VIRUS - \#1 Keeps banging your head in the hard drive!",
		"JEHOVAH'S WITNESS VIRUS - \#2 Deletes all but 144,000 select files.",
		"JERRY BROWN VIRUS - News your screen and flashes an 800 number.",
		"JERRY SPRINGER VIRUS - The chair next to your computer hurls toward you.",
		"JEWISH AMERICAN PRINCESS VIRUS - Perpetually books trips to Miami and buys jewelry online with your credit cards.",
		"JEWISH VIRUS - 8 days after delivery, your new computer looses the tip of its joystick, ouch!",
		"JIMMY HOFFA VIRUS - Your programs can never be found again.",
		"JOEY BUTTAFUCO VIRUS - Only attacks minor files.",
		"JURASSIC PARK VIRUS - Makes V20 computers more advanced than a 486 then duplicates the new computers.",
		"KENNETH STARR VIRUS - Completely examines every aspect of your computer, then compiles a complex report that discredits every aspect of your computer.",
		"LAPD VIRUS - It claims it feels threatened by other files on your PC and erases them in self-defense.",
		"LEFT-WING DRIVEL VIRUS - Deletes all monetary files, but keeps smiling and sending messages about how the economy is going to get better.",
		"LORENA BOBBITT VIRUS - \#1 Your hard disk turns into a 3.5 floppy.",
		"LORENA BOBBITT VIRUS - \#2 Reformats your hard drive to a 3.5 inch floppy, then discards it through Windows.",
		"LORENA BOBBITT VIRUS - \#3 Removes a vital part of your hard disk then re-attaches it, but that part will never work again.",
		"MARIO CUOMO VIRUS - It would be a great virus, but it refuses to run.",
		"MARTHA STEWART VIRUS - \#1 Takes all your files, sorts them by category and folds them into cute little dollies to be displayed on your desktop.",
		"MARTHA STEWART VIRUS - \#2 It takes over your PC and oh so tastefully alters your color palettes to lovely muted pastels.",
		"MCI VIRUS - Every three minutes it reminds you that you're paying too much for the AT\&T VIRUS.",
		"MICHAEL JACKSON VIRUS - Hard to identify because it is constantly altering its appearance. This virus won't harm your PC, but it will trash your car.",
		"MIKE TYSON VIRUS - Quits after two bytes.",
		"MONICA LEWINSKY VIRUS - Sucks all the memory out of your computer, then emails everyone about what it did.",
		"NATIONAL ENQUIRER VIRUS - It incessantly scans your files for evidence that you are cross-dressing, have been abducted by aliens, or are secretly dating Princess Di.",
		"NEW WORLD ORDER VIRUS - Probably harmless, but it makes a lot of people really mad just thinking about it.",
		"NIKE VIRUS - Just does it.",
		"O.J. SIMPSON VIRUS - \#1 You know it's guilty of trashing your system, but you just can't prove it.",
		"O.J. SIMPSON VIRUS - \#2 It claims that it did not, could not and would not delete two of your files and vows to find the virus that did it.",
		"OLLIE NORTH VIRUS - \#1 Causes your printer to become a paper shredder.",
		"OLLIE NORTH VIRUS - \#2 Plays a patriotic .WAV while it shreds your files.",
		"OPRAH WINFREY VIRUS - \#1 Your 200MB hard drive suddently shrinks to 80MB, and then slowly expands back to 200MB.",
		"OPRAH WINFREY VIRUS - \#2 Your 300MB hard drive suddently shrinks to 100MB, and then slowly expands to 200MB.",
		"ORAL ROBERTS VIRUS - Claims that if you don't send it a million dollars, its programmer will take it back.",
		"PAT BUCHANAN VIRUS - \#1 Your system works fine, but it complains loudly about foreign software. Frequently accompanies to the Right-to-Life and the Randall Terry Virus.",
		"PAT BUCHANAN VIRUS - \#2 Shifts all output to the extreme right of the screen.",
		"PAUL REVERE VIRUS - This revolutionary virus does not horse around. It warns you of impending hard disk attack -- once if by LAN, twice if by C:\>.",
		"PENTACOSTAL VIRUS - Keeps inviting you to click on web sites of elaborate beauticians.",
		"PINTO VIRUS - Sets your computer on fire.",
		"PBS VIRUS - Your programs stop every few minutes to ask for money.",
		"POLITICALLY CORRECT VIRUS - Never identifies itself as a 'VIRUS,' but instead refers to itself as an 'electronic micro-organism'.",
		"PONZI VIRUS - It logs onto your bank's computer and transfers \$1 into the accounts of the owners of the last 10 computers it was on. It then attaches itself to the next 10 items of mail you send.",
		"PROZAC VIRUS - Screws up your RAM, but your processor doesn't care.",
		"THE RAMBO VIRUS - Protects your CPU, but attacks any systems it percieves as enemies.",
		"RANDALL TERRY VIRUS - Prints 'Oh no you dont!' whenever you choose (A)bort from the (A)bort, (R)etry, (F)ail message.",
		"RIGHT-TO-LIFE VIRUS - Won't allow you to delete a file, regardless of how young it is. If you attempt to erase a file, it requires you to first see a counselor about possible alternatives.",
		"RIGHT-WING HARDLINER VIRUS - Won't allow any changes on your system, but keeps saying that things will get better as soon as it takes over the Whitehouse.",
		"ROMAN CATHOLIC VIRUS - Guilt trips the hell out of your hard drive so that it won't spin up any more.",
		"RONALD REAGAN VIRUS - \#1 Saves your data, but forgets where it's stored.",
		"RONALD REAGAN VIRUS - \#2 This virus creates serious problems in memory.",
		"ROSS PEROT VIRUS - \#1 Activates every component in your system, just before the whole damn thing quits.",
		"ROSS PEROT VIRUS - \#2 Runs for awhile, leaves the system, then re-appears, but with less effect.",
		"ROSS PEROT VIRUS - \#3 When you boot, it displayes a message saying that it is thinking of running. Then it scans the disk for competing operating systems, and if it finds any, shuts down immediately.",
		"SADDAM HUSSEIN VIRUS - Won't let you into any of your programs.",
		"SEARS VIRUS - Your data won't appear unless you buy new cables, power supply, and a set of shocks.",
		"SHARON STONE VIRUS - Makes a huge initial impact, when you forget it's there.",
		"SONNY BONO VIRUS - Just when you get surfing the web, a firewall appears out of nowhere.",
		"SPICE GIRLS VIRUS - Has no real function, but makes a pretty desktop.",
		"SPIKE LEE VIRUS - It makes your screen go totally black.",
		"STAR TREK VIRUS - Invades your system in places where no virus has gone before.",
		"STEVE FORBES VIRUS - All files are reported as the same size.",
		"TED TURNER VIRUS - Colorizes your monochrome monitor.",
		"TEENAGE VIRUS - You can get your PC to do what you want, but only after an interminable argument that leaves you feeling horribly guilty.",
		"TEXAS VIRUS - Makes sure that it's bigger than any other file.",
		"TIM ALLEN VIRUS - Appears helpful, only to destroy your hard drive upon contact.",
		"TIPPER GORE VIRUS - When you attempt to play any sound file, it pops up a warning window stating that some lyrics may be unsuitable for children.",
		"TITANIC VIRUS (A strain of the Lewinsky virus) - Your whole computer goes down.",
		"TONYA HARDING VIRUS - Turns your .BAT files into lethal weapons.",
		"TYPE-A VIRUS - It makes your hard drive hard driven.",
		"UNITARIAN VIRUS - \#1 Opens a LOT of windows, but for no apparent reason.",
		"UNITARIAN VIRUS - \#2 It opens all windows and lets you view back into your computers life as an 8088.",
		"VAMPYRE VIRUS - Your PC can operate only at night, and its performance really sucks.",
		"VIAGRA VIRUS - Makes a new hard drive out of an old floppy.",
		"WARREN COMMISSION VIRUS - Won't allow you to open your files for 75 years.",
		"WILLIARD SCOTT VIRUS - Keeps track of all family birthdays and renders verbose birthday wishes each time you request weather predictions.",
		"WINDOWS 95 VIRUS - And you thought it was an operating system!",
		"WODDY ALLEN VIRUS - Bypasses the motherboard and turns on a daughter card.",
		"X-FILES VIRUS - all your icons start shapeshifting.",
	);

	# Get the total count.
	print "Virus Joke Count: " . scalar(@virus) . "\n";

	# Pick a random joke.
	my $reply = $virus [ int(rand(scalar(@virus))) ];

	# Return the reply.
	return $reply;
}

{
	Category => 'Random Stuff',
	Description => 'Virus Jokes',
	Usage => '!virus',
	Listener => 'All',
};