#      .   .             <CKS Juggernaut>
#     .:...::     Command Name // !insult
#    .::   ::.     Description // Get a random insult.
# ..:;;. ' .;;:..        Usage // !insult
#    .  '''  .     Permissions // Public
#     :;,:,;:         Listener // All Listeners
#     :     :        Copyright // 2004 Chaos AI Technology

sub insult {
	my ($self,$client,$msg,$listener) = @_;

	# List of adjectives.
	my @adj = (
		"amorphous ",
		"annoying ",
		"appaling ",
		"asinine ",
		"atrocious ",
		"bad breathed ",
		"bad tempered ",
		"bewildered ",
		"bizarre ",
		"blithering ",
		"blundering ",
		"boring ",
		"brainless ",
		"bungling ",
		"cantankerous ",
		"clueless ",
		"confused ",
		"contemptible ",
		"cranky ",
		"creepy ",
		"crooked ",
		"crotchety ",
		"crude ",
		"decrepit ",
		"deeply disturbed ",
		"demented ",
		"depraved ",
		"deranged ",
		"despicable ",
		"detestable ",
		"dim-witted ",
		"disdainful ",
		"disgraceful ",
		"disgusting ",
		"dismal ",
		"distasteful ",
		"distended ",
		"dreadful ",
		"drivelling ",
		"dull ",
		"dumb ",
		"embarrassing ",
		"evil-smelling ",
		"facile ",
		"feeble-minded ",
		"flea-bitten ",
		"fractious ",
		"frantic ",
		"friendless ",
		"glutinous ",
		"god-awful ",
		"good-for-nothing ",
		"goofy ",
		"grotesque ",
		"hopeless ",
		"hypocritical ",
		"ignorant ",
		"illiterate ",
		"inadequate ",
		"inane ",
		"incapable ",
		"incompetent ",
		"incredible ",
		"indecent ",
		"indescrible ",
		"inept ",
		"infantile ",
		"infuriating ",
		"inhuman ",
		"insane ",
		"insignificant ",
		"insufferable ",
		"irrational ",
		"irresponsible ",
		"lackluster ",
		"laughable ",
		"lazy ",
		"loathsome ",
		"low budget ",
		"malodorous ",
		"misanthropic ",
		"miserable ",
		"monotonous ",
		"nauseating ",
		"neurotic ",
		"obese ",
		"oblivious ",
		"obnoxious ",
		"obsequious ",
		"opinionated ",
		"outrageous ",
		"pathetic ",
		"perverted ",
		"pitiable ",
		"pitiful ",
		"pointless ",
		"pompous ",
		"predictable ",
		"preposterous ",
		"psychotic ",
		"pustulent ",
		"rat-faced ",
		"recalcitrant ",
		"reprehensible ",
		"repulsive ",
		"retarded ",
		"revolting ",
		"rediculous ",
		"rotund ",
		"shameless ",
		"sick ",
		"sickening ",
		"sleazy ",
		"sloppy ",
		"stupid ",
		"superficial ",
		"sycophantic ",
		"tacky ",
		"testy ",
		"ugly ",
		"unbelievable ",
		"uncouth ",
		"uneducated ",
		"ungodly ",
		"unholy ",
		"unimpressive ",
		"upsetting ",
		"useless ",
		"vile ",
		"violent ",
		"vomitous ",
		"witless ",
		"worthless ",
	);
	my @first = (
		"accumulation of ",
		"apology for ",
		"assortment of ",
		"bag of ",
		"ball of ",
		"barrel of ",
		"blob of ",
		"bowl of ",
		"box of ",
		"bucket of ",
		"bunch of ",
		"cake of ",
		"clump of ",
		"collection of ",
		"container of ",
		"contribution of ",
		"crate of ",
		"crock of ",
		"chunk of ",
		"eruption of ",
		"excuse for ",
		"glob of ",
		"heap of ",
		"load of ",
		"loaf of ",
		"lump of ",
		"mass of ",
		"mound of ",
		"mountain of ",
		"pile of ",
		"sack of ",
		"shovel-full of ",
		"stack of ",
		"toilet-full of ",
		"truckload of ",
		"tub of ",
		"vat of ",
	);
	my @second = (
		"cheesy ",
		"clammy ",
		"contaminated ",
		"crummy ",
		"crusty ",
		"cute ",
		"decaying ",
		"decomposed ",
		"defective ",
		"dehydrated ",
		"dirty ",
		"fermenting ",
		"festering ",
		"fly-covered ",
		"foreign ",
		"fornicating ",
		"fossilised ",
		"foul ",
		"freeze dried ",
		"fresh ",
		"fusty ",
		"grimey ",
		"grisly ",
		"gross ",
		"greusome ",
		"imitation ",
		"industrial-strength ",
		"infected ",
		"infested ",
		"laughable ",
		"lousy ",
		"malignant ",
		"mildewed ",
		"musty ",
		"moldy ",
		"mutilated ",
		"nasty ",
		"nauseating ",
		"old ",
		"petrified ",
		"polluted ",
		"putrid ",
		"radioactive ",
		"rancid ",
		"raunchy ",
		"recycled ",
		"rotten ",
		"sloppy ",
		"sloshy ",
		"smelly ",
		"soggy ",
		"soppy ",
		"spoiled ",
		"stale ",
		"steaming ",
		"stenchy ",
		"stinky ",
		"sun-ripened ",
		"synthetic ",
		"unpleasant ",
		"yeasty ",
		"wormy ",
	);
	my @third = (
		"aardvark effluent",
		"ape puke",
		"armpit hairs",
		"baboon asses",
		"bat dumplings",
		"bile",
		"braised pus",
		"buffalo excrement",
		"buzzard barf",
		"camel fleas",
		"donkey manure",
		"chicken guts",
		"cigar butts",
		"cockroaches",
		"compost",
		"cow crud",
		"cow pies",
		"coyote snot",
		"dandruff flakes",
		"dirty underwear",
		"dog barf",
		"dog meat",
		"dog phlegm",
		"donkey droppings",
		"ear wax",
		"eel guts",
		"foot fungus",
		"dung",
		"toe jam",
		"garbage",
		"hemorrhoids",
		"hippo vomit",
		"smegma",
		"hog livers",
		"jock straps",
		"kangaroo vomit",
		"knob cheese",
		"leprosy scabs",
		"llama spit",
		"herpes scabs",
		"maggot brains",
		"monkey shit",
		"moose entrails",
		"mule froth",
		"nasal hairs",
		"naval lint",
		"parrot droppings",
		"nose pickings",
		"penile warts",
		"pig bowels",
		"pig slop",
		"pigeon bombs",
		"pimple pus",
		"pimple squeezings",
		"puke lumps",
		"pustulence",
		"rabbit raisins",
		"rat bogies",
		"rodent droppings",
		"sewage",
		"rubbish",
		"sewer seepage",
		"shark snot",
		"sheep droppings",
		"sinus clots",
		"sinus drainage",
		"skid marks",
		"skunk waste",
		"sludge",
		"slug slime",
		"snake innards",
		"stable sweepings",
		"stomach acid",
		"swamp mud",
		"sweat socks",
		"swime remains",
		"toad tumors",
		"tripe",
		"turkey puke",
		"testicle warts",
		"vulture gizzards",
		"walrus blubber",
		"weasel warts",
		"whale waste",
		"wookie hair",
		"zit cheeze",
	);

	# Get random values.
	my $one = $adj [ int(rand(scalar(@adj))) ];
	my $two = $first [ int(rand(scalar(@first))) ];
	my $three = $second [ int(rand(scalar(@second))) ];
	my $four = $third [ int(rand(scalar(@third))) ];

	# Return this insult.
	return "You " . $one . $two . $three . $four . ".";
}

{
	Category => 'Fun & Games',
	Description => 'Random Insults (a must-see)',
	Usage => '!insults',
	Listener => 'All',
};